// <auto-generated />
namespace WinForm.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FixCus12 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixCus12));
        
        string IMigrationMetadata.Id
        {
            get { return "201805070605232_FixCus12"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
