// <auto-generated />
namespace WinForm.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class editStatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editStatus));
        
        string IMigrationMetadata.Id
        {
            get { return "201805100834535_editStatus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
